# Generated by Django 4.0.4 on 2022-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(default='Admin', to='main_page.author'),
        ),
    ]
