# Generated by Django 4.0.4 on 2022-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_author_alter_news_title_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_him',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='author',
            name='want_to_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
    ]
