# Generated by Django 4.0.4 on 2022-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_author_about_him_author_age_author_photo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(default='Ukraine', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(default='+380000000000', max_length=12),
        ),
    ]
