# Generated by Django 4.0.4 on 2022-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_author_address_author_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
    ]
