# Generated by Django 4.0.4 on 2022-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='-', max_length=20)),
                ('second', models.CharField(default='-', max_length=20)),
                ('third', models.CharField(default='-', max_length=20)),
                ('fourth', models.CharField(default='-', max_length=20)),
                ('fifth', models.CharField(default='-', max_length=20)),
                ('sixth', models.CharField(default='-', max_length=20)),
                ('seventh', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('subjects', models.ManyToManyField(to='schedule.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount_students', models.IntegerField(default=0)),
                ('schedule', models.ManyToManyField(to='schedule.dayofweak')),
            ],
        ),
    ]
