# Generated by Django 4.0.4 on 2022-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweak',
            name='subjects',
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='fifth',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='first',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='fourth',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='second',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='seventh',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='sixth',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='third',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
