# Generated by Django 4.0.4 on 2022-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_dayofweak_subjects_dayofweak_fifth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='-', max_length=20)),
                ('second', models.CharField(default='-', max_length=20)),
                ('third', models.CharField(default='-', max_length=20)),
                ('fourth', models.CharField(default='-', max_length=20)),
                ('fifth', models.CharField(default='-', max_length=20)),
                ('sixth', models.CharField(default='-', max_length=20)),
                ('seventh', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='first',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='second',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='seventh',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='dayofweak',
            name='third',
        ),
        migrations.AddField(
            model_name='dayofweak',
            name='subjects',
            field=models.ManyToManyField(to='schedule.subjects'),
        ),
    ]
