# Generated by Django 4.0.4 on 2022-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=1)),
                ('position', models.CharField(default='', max_length=30)),
                ('about_him', models.TextField(default=' ')),
                ('education', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
